### ISSUE TITLE
teensy2 compile error / analog_pin_to_channel_PGM

### ISSUE THREAD

**Issue by loopmasta** [sensorium/Mozzi#10]
I am trying to get Mozzi running with a teensy2 but i get this error message.

Mozzi/mozzi_analog.cpp.o: In function `adcStartConversion(unsigned char)':
.../Documents/Arduino/libraries/Mozzi/mozzi_analog.cpp:115: undefined reference to`analog_pin_to_channel_PGM'

A fix found in a issue opened by Nanoblender does not seem to work.

**Comment by autotel** [comment]
Hello! Three years from this post. I am also having trouble to get mozzi working on a teensy 2.0. The error is lengthier; and far from my understanding:
`In file included from C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\examples\01.Basics\Sinewave\Sinewave.ino:17:0:
C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2/MozziGuts.h:151:2: warning: #warning "AUDIO_MODE is set to STANDARD_PLUS in mozzi_config.h.  If things sound wrong, check if STANDARD_PLUS is the correct AUDIO_MODE for your sketch." [-Wcpp]
#warning "AUDIO_MODE is set to STANDARD_PLUS in mozzi_config.h.  If things sound wrong, check if STANDARD_PLUS is the correct AUDIO_MODE for your sketch."
^
In file included from C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\MozziGuts.cpp:19:0:
C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\MozziGuts.h:151:2: warning: #warning "AUDIO_MODE is set to STANDARD_PLUS in mozzi_config.h.  If things sound wrong, check if STANDARD_PLUS is the correct AUDIO_MODE for your sketch." [-Wcpp]
#warning "AUDIO_MODE is set to STANDARD_PLUS in mozzi_config.h.  If things sound wrong, check if STANDARD_PLUS is the correct AUDIO_MODE for your sketch."
^
In file included from C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\MozziGuts.cpp:29:0:
C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\utility/TimerOne.h: In function 'void startMozzi(int)':
C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\utility/TimerOne.h:90:22: warning: 'cycles' may be used uninitialized in this function [-Wmaybe-uninitialized]
pwmPeriod = cycles;
^
C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\utility/TimerOne.h:73:17: note: 'cycles' was declared here
unsigned long cycles;
^
C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\mozzi_utils.cpp: In function 'long int trailingZeros(long unsigned int)':
C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\mozzi_utils.cpp:12:24: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
return (*(uint32_t *)&f >> 23) - 0x7f;
^
C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\utility\FrequencyTimer2.cpp:84:65: error: no 'void FrequencyTimer2::setPeriodMicroSeconds(long unsigned int)' member function declared in class 'FrequencyTimer2'
void FrequencyTimer2::setPeriodMicroSeconds(unsigned long period) {
^
C:\Users\joaquin\Documents\Arduino\libraries\Mozzi-1.0.2\utility\FrequencyTimer2.cpp:90:62: error: no 'void FrequencyTimer2::setPeriodCPUCycles(long unsigned int)' member function declared in class 'FrequencyTimer2'
void FrequencyTimer2::setPeriodCPUCycles(unsigned long period){
^
exit status 1
Error compiling.
`

**Comment by tfry-git** [comment]
Well this report is rather old by now. @autotel are you still with us? Do you still see this error, in this, or a more recent release of Mozzi?

If so, I guess that it is a problem with a clash with a separately installed "FrequencyTimer2" library. Could you test, whether the following helps:
In Arduino\libraries\Mozzi-1.0.2\utility\FrequencyTimer2.cpp , near the top, replace `#include <FrequencyTimer2.h>` with `#include "FrequencyTimer2.h"` (i.e. quotes instead of angle brackets).

Thanks!
